"""Initial migration

Revision ID: 1f84e2b6843a
Revises:
Create Date: 2024-07-31 21:26:31.663659+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f84e2b6843a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ledger", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("project_key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_action"), "event", ["action"], unique=False)
    op.create_index(
        op.f("ix_event_project_key"), "event", ["project_key"], unique=False
    )
    op.create_table(
        "latest_ledger",
        sa.Column("ledger", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("ledger"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("latest_ledger")
    op.drop_index(op.f("ix_event_project_key"), table_name="event")
    op.drop_index(op.f("ix_event_action"), table_name="event")
    op.drop_table("event")
    # ### end Alembic commands ###
